CREATE TABLE PRO_LINK_PRO_PRICE
(
    LINK_PRO_CODE VARCHAR(30) NOT NULL,
    PRICE_DT      DATE        NOT NULL,
    CREATE_DT     DATETIME2(6) NOT NULL,
    MODIFY_DT     DATETIME2(6),
    CONSTRAINT PK_PRO_LINK_PRO_PRICE PRIMARY KEY (LINK_PRO_CODE, PRICE_DT)
);

CREATE TABLE PRO_LINK_PRO_PRICE_TEMP
(
    LINK_PRO_CODE VARCHAR(30) NOT NULL,
    PRICE_DT      DATE        NOT NULL,
    MODIFY_DT     DATETIME2(6),
    CONSTRAINT PK_PRO_LINK_PRO_PRICE_TEMP PRIMARY KEY (LINK_PRO_CODE, PRICE_DT)
);